export default {
  LIGHT_BLUE: '#E5F4FD',
  SKY_BLUE: '#9CC9E2',
  WHITE: '#F9F9F9',
  BRIGHT_WHITE: '#FFF',
  LIGHT_GRAY: '#EEE',
  GRAY: '#999',
  BLACK: '#333',
  MUSTARD: '#FBBC05',
  DARK_BLUE: '#1F4860'
}