const ALL_CONSTANT = {
  NEXT: 'next',
  BACK_TO_DASHBOARD: 'back_to_dashboard',
  START_QUESTION: 'start_question',
  DEFINITION: 'definition',
  SENTENCES: 'sentences',
  QUESTIONS_SMALL: 'questions',
  PROGRESS: 'progress',
  CURRENT_GAME_POSITION: 'currentGamePosition',
  CURRENT_LEVEL: 'currentLevel',
  LEARNING_WORDS: 'learningWords',
  LEVELS_COUNT: 13,
  FETCHING: 'Fetching',
  USERS: 'users',
  WORDS: 'words',
  QUESTIONS: 'questions',
  END_SESSION: 'END SESSION',
  GET_ONE_MORE: 'GET ONE MORE',
  LIGHT: 'LIGHT',
  DARK: 'DARK',
  INFORMATION: 'information',
  START_LEARNING: 'START LEARNING',
  SENTENCE: 'Sentence',
  OPTION: 'option',
  QUESTION: 'question',
  QUESTION_TITLECASE: 'Question',
  WORD: 'word',
  NAME_REQUIRED: 'Name is required!',
  EMAIL_REQUIRED: 'Email is required!',
  FEEDBACK_REQUIRED: 'Feedback is required!',
  WORD_TITLECASE: 'Word',
  UI_DESIGN: 'UI/Design',
  FUNCTIONALITY: 'Functionality',
  OTHER: 'Other',
  LEARN_MORE: 'Learn More',
};

export default ALL_CONSTANT;
