const CONSTANTS = {
  ALL_WORDS: 'allWords',
  ANTONYM: 'antonym',
  ANTONYMS: 'Antonyms',
  APP_TITLE: 'Shabadavali.',
  BACK: 'Back',
  DASHBOARD: 'Dashboard',
  DESCRIPTION: 'Made by Khalis Foundation',
  EXAMPLES: 'Examples',
  GURFATEH_PUNJABI: 'ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ ॥ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਿਹ ॥',
  SSA_PUNJABI: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ',
  LOGIN_INFO: `Before you start adding new words to your 
    vocabulary, we just need some information from you.`,
  NUM_COINS: 13,
  ENTER_DETAILS: 'Please enter your details',
  LOADING: 'Loading...',
  OR: 'or',
  PROFILE: 'Profile',
  QUESTIONS: 'Questions',
  QUESTIONS_TO_GO: 'QUESTIONS TO GO TO YOUR NEXT NANAK COIN!!',
  SETTINGS: 'Settings',
  SIGN_IN: 'Sign In',
  SIGN_IN_WITH_GOOGLE: 'Sign In with Google',
  SIGN_OUT: 'Sign Out',
  SIGN_UP: 'Sign Up',
  SHASHA: 'ਸ਼',
  SYNONYM: 'synonym',
  SYNONYMS: 'Synonyms',
  TITLE: 'Shabadavali',
  TOTAL_NUM_QUESTIONS: 13,
  WELCOME: 'Welcome',
  WORD_NOT_FOUND: 'Word not found',
  GET_ONE_MORE: 'GET ONE MORE',
  GREAT_JOB: 'Great Job! ਵਧਾਇਆਂ',
  NANAK_COIN_DESC: 'You got your 14th Nanak coin!',
  WORDS_YOU_LEARNT: 'Words you learnt',
  COINS_DESC: 'Total number of Nanak Coins',
  COINS_DESC2: 'WORDS TO GO FOR YOUR NEXT COIN!!',
  RANDOM_WORD_TITLE: 'Random word of the Day',
  EXPLORE_WORD: 'Explore Word',
};

export default CONSTANTS;
