const CONSTANTS = {
  ALL_WORDS: 'allWords',
  ANTONYM: 'antonym',
  ANTONYMS: 'Antonyms',
  APP_TITLE: 'Shabadavali.',
  BACK: 'Back',
  COINS_DESC: 'Total number of Nanak Coins',
  COINS_DESC2: 'QUESTIONS TO GO FOR YOUR NEXT COIN!!',
  CONFIRM_PASSWORD: 'Confirm Password',
  DASHBOARD: 'Dashboard',
  DESCRIPTION: 'Made by Khalis Foundation',
  EMAIL: 'Email',
  EMAIL_VERIFICATION_SENT: 'Email verification sent to your inbox!',
  ENTER_DETAILS: 'Please enter your details',
  ENTER_VALID_EMAIL: 'Please enter a valid email address',
  ERROR: 'Error',
  ERROR_PWD:
    'Password must contain at least 8 characters, one uppercase, one lowercase and one number',
  EXAMPLES: 'Examples',
  EXPLORE_WORD: 'Explore Word',
  FIFTH_QUESTION: 'You completed your 5th question!',
  FILL_ALL_FIELDS: 'Please fill all the fields',
  GET_ONE_MORE: 'GET ONE MORE',
  GRAY: 'gray',
  GREAT_JOB: 'Great Job!',
  GURFATEH_PUNJABI: 'ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ ॥ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫਤਿਹ ॥',
  GURMUKHI: 'gurmukhi',
  KNOW_MORE: 'Know More',
  LOADING: 'Loading...',
  LOGIN_INFO: `Before you start adding new words to your 
    vocabulary, we just need some information from you.`,
  LOGGING_OUT: 'Logging out...',
  NAME: 'Name',
  NUM_COINS: 13,
  OR: 'or',
  PASSWORD: 'Password',
  PASSWORDS_DONT_MATCH: 'Passwords do not match!',
  PROFILE: 'Profile',
  PUNJABI_5: '੫',
  QUESTIONS: 'Questions',
  QUESTIONS_TO_GO: 'QUESTIONS TO GO FOR YOUR NEXT NANAK COIN!!',
  RANDOM_WORD_TITLE: 'Random word of the Day',
  RED: 'red',
  SEMANTICS_PRAISE: 'ਸ਼ਾਬਾਸ਼! (Well done) Ready for the challenges?',
  SETTINGS: 'Settings',
  SIGN_IN: 'Sign In',
  SIGN_IN_WITH_GOOGLE: 'Sign In with Google',
  SIGN_OUT: 'Sign Out',
  SIGN_UP: 'Sign Up',
  SHASHA: 'ਸ਼',
  SSA_PUNJABI: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ',
  SUCCESS: 'Success',
  SYNONYM: 'synonym',
  SYNONYMS: 'Synonyms',
  TITLE: 'Shabadavali',
  TOTAL_NUM_QUESTIONS: 13,
  WELCOME: 'Welcome',
  WORD_NOT_FOUND: 'Word not found',
  WORDS_YOU_LEARNT: 'Words you learnt',
};

export default CONSTANTS;
